/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author zakariae
 */
public class Acceuil extends javax.swing.JFrame {

    public Acceuil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        javax.swing.JButton Seconnecter = new javax.swing.JButton();
        creeruncompte = new javax.swing.JButton();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        numerote = new javax.swing.JTextField();
        motdepasse = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        try {
            jLabel1 =(javax.swing.JLabel)java.beans.Beans.instantiate(getClass().getClassLoader(), "View.Acceuil_jLabel1");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SportOrg");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 200, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,170));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setFocusCycleRoot(true);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Seconnecter.setBackground(new java.awt.Color(0, 51, 255));
        Seconnecter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Seconnecter.setForeground(new java.awt.Color(255, 255, 255));
        Seconnecter.setText("Se connecter");
        Seconnecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeconnecterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SeconnecterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SeconnecterMouseExited(evt);
            }
        });
        Seconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeconnecterActionPerformed(evt);
            }
        });
        jPanel2.add(Seconnecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 245, -1));

        creeruncompte.setBackground(new java.awt.Color(0, 255, 0));
        creeruncompte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        creeruncompte.setForeground(new java.awt.Color(255, 255, 255));
        creeruncompte.setText("Créer un compte");
        creeruncompte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creeruncompteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creeruncompteMouseExited(evt);
            }
        });
        creeruncompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creeruncompteActionPerformed(evt);
            }
        });
        jPanel2.add(creeruncompte, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Création de compte");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        numerote.setBackground(new java.awt.Color(240, 242, 245));
        numerote.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        numerote.setForeground(new java.awt.Color(153, 153, 153));
        numerote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numeroteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                numeroteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numeroteMouseExited(evt);
            }
        });
        numerote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroteActionPerformed(evt);
            }
        });
        jPanel2.add(numerote, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 250, 30));

        motdepasse.setBackground(new java.awt.Color(240, 242, 245));
        motdepasse.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        motdepasse.setForeground(new java.awt.Color(153, 153, 153));
        motdepasse.setText(" ");
        motdepasse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                motdepasseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                motdepasseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                motdepasseMouseExited(evt);
            }
        });
        motdepasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motdepasseActionPerformed(evt);
            }
        });
        jPanel2.add(motdepasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 250, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel2.setText("Mot de passe");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel6.setText("Identifiant agent");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 290, 300));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creeruncompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creeruncompteActionPerformed
        // TODO add your handling code here:
        Compte compte = new Compte();
        compte.setVisible(true);
        compte.setLocationRelativeTo(null);
        compte.setTitle("Création d'un nouveau compte");
        this.dispose();
    }//GEN-LAST:event_creeruncompteActionPerformed

    private void SeconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeconnecterActionPerformed
        if (checkEmtyFieldAc()) {
            JOptionPane.showMessageDialog(null, "Il'y a des cases vides \n Il faut les remplir svp", "Information d'erreur", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_SeconnecterActionPerformed

    private void SeconnecterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeconnecterMouseEntered
        // TODO add your handling code here:
        Seconnecter.setBackground(new Color(0, 102, 108));
    }//GEN-LAST:event_SeconnecterMouseEntered

    private void SeconnecterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeconnecterMouseExited
        // TODO add your handling code here:
        Seconnecter.setBackground(new Color(0, 51, 255));
    }//GEN-LAST:event_SeconnecterMouseExited

    private void creeruncompteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creeruncompteMouseEntered
        // TODO add your handling code here:
        creeruncompte.setBackground(new Color(0, 153, 0));
    }//GEN-LAST:event_creeruncompteMouseEntered

    private void creeruncompteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creeruncompteMouseExited
        // TODO add your handling code here:
        creeruncompte.setBackground(new Color(0, 255, 0));
    }//GEN-LAST:event_creeruncompteMouseExited

    private void numeroteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroteActionPerformed

    private void motdepasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motdepasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motdepasseActionPerformed

    private void numeroteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroteMouseClicked
        numerote.setText(null);
    }//GEN-LAST:event_numeroteMouseClicked

    private void numeroteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroteMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        numerote.setBorder(border);
        numerote.setForeground(Color.black);
    }//GEN-LAST:event_numeroteMouseEntered

    private void numeroteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroteMouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(141, 142, 143));
        numerote.setBorder(border);
        numerote.setForeground(Color.black);
    }//GEN-LAST:event_numeroteMouseExited

    private void motdepasseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_motdepasseMouseClicked
        motdepasse.setText(null);
    }//GEN-LAST:event_motdepasseMouseClicked

    private void motdepasseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_motdepasseMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        motdepasse.setBorder(border);
        motdepasse.setForeground(Color.black);
    }//GEN-LAST:event_motdepasseMouseEntered

    private void motdepasseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_motdepasseMouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(141, 142, 143));
        motdepasse.setBorder(border);
        motdepasse.setForeground(Color.black);
    }//GEN-LAST:event_motdepasseMouseExited

    private void SeconnecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeconnecterMouseClicked

    }//GEN-LAST:event_SeconnecterMouseClicked

    private boolean checkEmtyFieldAc() {
        return (motdepasse.getText().equals("") || numerote.getText().equals(""));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Acceuil acceuil = new Acceuil();
                acceuil.setVisible(true);
                acceuil.setTitle("SportOrg");
                acceuil.setLocationRelativeTo(null);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creeruncompte;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField motdepasse;
    private javax.swing.JTextField numerote;
    // End of variables declaration//GEN-END:variables
}
