/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author zakariae
 */
public class Compte extends javax.swing.JFrame {

    /**
     * Creates new form Compte
     */
    public Compte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fermeture = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        mtp2 = new javax.swing.JTextField();
        mtp = new javax.swing.JTextField();
        sinscrire = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(129, 30, 104));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255,170));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255,80));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Urdu Typesetting", 1, 24)); // NOI18N
        jLabel2.setText("Inscription  agent");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 208, 40));

        fermeture.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fermeture.setText("X");
        fermeture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fermeture.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fermeture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermetureMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fermetureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fermetureMouseExited(evt);
            }
        });
        jPanel5.add(fermeture, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 0, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        prenom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prenom.setForeground(new java.awt.Color(204, 204, 204));
        prenom.setText("Prénom");
        prenom.setSelectionColor(new java.awt.Color(204, 204, 204));
        prenom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prenomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prenomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prenomMouseExited(evt);
            }
        });
        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });
        jPanel4.add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 188, 34));

        nom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nom.setForeground(new java.awt.Color(204, 204, 204));
        nom.setText("Nom");
        nom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nomMouseExited(evt);
            }
        });
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        jPanel4.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 190, 34));

        numero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numero.setForeground(new java.awt.Color(204, 204, 204));
        numero.setText("Numéro de mobile");
        numero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numeroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                numeroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numeroMouseExited(evt);
            }
        });
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        jPanel4.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 188, 34));

        mtp2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mtp2.setForeground(new java.awt.Color(204, 204, 204));
        mtp2.setText("Confirmer le mot de passe");
        mtp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mtp2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mtp2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mtp2MouseExited(evt);
            }
        });
        jPanel4.add(mtp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 190, 34));

        mtp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mtp.setForeground(new java.awt.Color(204, 204, 204));
        mtp.setText("Mot de passe");
        mtp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mtpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mtpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mtpMouseExited(evt);
            }
        });
        jPanel4.add(mtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 188, 34));

        sinscrire.setBackground(new java.awt.Color(0, 255, 0));
        sinscrire.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sinscrire.setForeground(new java.awt.Color(255, 255, 255));
        sinscrire.setText("S'inscrire");
        sinscrire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinscrireMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sinscrireMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sinscrireMouseExited(evt);
            }
        });
        sinscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinscrireActionPerformed(evt);
            }
        });
        jPanel4.add(sinscrire, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 202, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel6.setText("Confirmer le mot de passe");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 270, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel7.setText("Nom");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel8.setText("Prénom");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel9.setText("Numéro de mobile");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel10.setText("Mot de passe");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 270, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Image1.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prenomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prenomMouseClicked
        prenom.setText(null);
    }//GEN-LAST:event_prenomMouseClicked

    private void sinscrireMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinscrireMouseEntered
        sinscrire.setBackground(new Color(0, 153, 0));

    }//GEN-LAST:event_sinscrireMouseEntered

    private void sinscrireMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinscrireMouseExited
        sinscrire.setBackground(new Color(0, 255, 0));
    }//GEN-LAST:event_sinscrireMouseExited

    private void prenomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prenomMouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(141, 142, 143));
        prenom.setBorder(border);
        prenom.setForeground(new Color(204, 204, 204));

    }//GEN-LAST:event_prenomMouseExited

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed


    }//GEN-LAST:event_prenomActionPerformed

    private void prenomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prenomMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
        prenom.setBorder(border);
        prenom.setForeground(Color.BLACK);

    }//GEN-LAST:event_prenomMouseEntered

    private void nomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
        nom.setBorder(border);
        nom.setForeground(Color.black);


    }//GEN-LAST:event_nomMouseEntered

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
        nom.setBorder(border);
    }//GEN-LAST:event_nomActionPerformed

    private void nomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomMouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(141, 142, 143));
        nom.setBorder(border);
        nom.setForeground(new Color(204, 204, 204));

    }//GEN-LAST:event_nomMouseExited

    private void numeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
        numero.setBorder(border);
        numero.setForeground(Color.black);

    }//GEN-LAST:event_numeroMouseEntered

    private void numeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroMouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(141, 142, 143));
        numero.setBorder(border);
        numero.setForeground(new Color(204, 204, 204));

    }//GEN-LAST:event_numeroMouseExited

    private void mtpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtpMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
        mtp.setBorder(border);
        mtp.setForeground(Color.black);

    }//GEN-LAST:event_mtpMouseEntered

    private void mtpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtpMouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(141, 142, 143));
        mtp.setBorder(border);
        mtp.setForeground(new Color(204, 204, 204));

    }//GEN-LAST:event_mtpMouseExited

    private void mtp2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtp2MouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
        mtp2.setBorder(border);
        mtp2.setForeground(Color.black);

    }//GEN-LAST:event_mtp2MouseEntered

    private void mtp2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtp2MouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(141, 142, 143));
        mtp2.setBorder(border);
        mtp2.setForeground(new Color(204, 204, 204));

    }//GEN-LAST:event_mtp2MouseExited

    private void sinscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinscrireActionPerformed
        if (checkEmtyFields()) {
            JOptionPane.showMessageDialog(null, "il'y a des cases vides \n il faut les remplir !", "Information d'erreur", JOptionPane.ERROR_MESSAGE);
        } else {
            InscriptionReussi inr = new InscriptionReussi();
            inr.setVisible(true);
            inr.setLocationRelativeTo(null);
            inr.setTitle("Création a été par succes");
            this.dispose();
        }
    }//GEN-LAST:event_sinscrireActionPerformed

    private void mtp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtp2MouseClicked
        mtp2.setText(null);
    }//GEN-LAST:event_mtp2MouseClicked

    private void mtpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtpMouseClicked
        mtp.setText(null);
    }//GEN-LAST:event_mtpMouseClicked

    private void numeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroMouseClicked
        numero.setText(null);
    }//GEN-LAST:event_numeroMouseClicked

    private void nomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomMouseClicked
        nom.setText(null);
    }//GEN-LAST:event_nomMouseClicked

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void sinscrireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinscrireMouseClicked

    }//GEN-LAST:event_sinscrireMouseClicked

    private void fermetureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermetureMouseExited
        Border border1 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        fermeture.setBorder(border1);
        fermeture.setForeground(Color.black);
    }//GEN-LAST:event_fermetureMouseExited

    private void fermetureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermetureMouseEntered
        Border border1 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        fermeture.setBorder(border1);
        fermeture.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_fermetureMouseEntered

    private void fermetureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermetureMouseClicked
        // TODO add your handling code here:
        Acceuil acceuil = new Acceuil();
        acceuil.setVisible(true);
        acceuil.setLocationRelativeTo(null);
        acceuil.setTitle("Gestion des Terrains");
        this.dispose();
    }//GEN-LAST:event_fermetureMouseClicked

    private boolean checkEmtyFields() {
        return (prenom.getText().equals("") || nom.getText().equals("") || numero.getText().equals("") || mtp.getText().equals("") || mtp2.getText().equals(""));

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Compte compte = new Compte();
                compte.setVisible(true);
                compte.setLocationRelativeTo(null);
                compte.setTitle("Création d'un nouveau compte");

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fermeture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField mtp;
    private javax.swing.JTextField mtp2;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField prenom;
    private javax.swing.JButton sinscrire;
    // End of variables declaration//GEN-END:variables
}
